# Generated by Django 4.0.3 on 2022-03-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='album/'),
        ),
    ]
