# Generated by Django 4.0.3 on 2022-03-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_album_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songFile',
            field=models.FileField(blank=True, default=None, upload_to='audio/'),
        ),
    ]
